[http.middlewares.default-ipwhitelist.ipWhiteList]
sourceRange = [ "192.168.100.0/24" ]

[tls.stores.default.defaultGeneratedCert]
resolver = "letsencrypt"

  [tls.stores.default.defaultGeneratedCert.domain]
  main = "mapeus.xyz"
  sans = [
  "portainer-sc.mapeus.xyz",
  "jellyfin-sc.mapeus.xyz",
  "qbittorrent-sc.mapeus.xyz",
  "radarr-sc.mapeus.xyz",
  "prowlarr-sc.mapeus.xyz",
  "bazarr-sc.mapeus.xyz",
  "jellyseerr-sc.mapeus.xyz",
  "sonarr-sc.mapeus.xyz",
  "grafana-sc.mapeus.xyz"
]
