[global]
sendAnonymousUsage = false

[api]
dashboard = true
insecure = true
debug = false

[entryPoints.web]
address = ":80"

[entryPoints.web.http.redirections.entryPoint]
to = "websecure"
scheme = "https"

[entryPoints.websecure]
address = ":443"

[serversTransport]
insecureSkipVerify = true

[providers.docker]
endpoint = "unix:///var/run/docker.sock"
exposedByDefault = false

[providers.file]
directory = "/etc/traefik"
watch = true

[certificatesResolvers.letsencrypt.acme]
email = "alvesmarcelocf@proton.me"
storage = "/certs/acme.json"

  [certificatesResolvers.letsencrypt.acme.dnsChallenge]
  provider = "cloudflare"
  resolvers = [ "1.1.1.1:53" ]

[log]
filePath = "/var/log/traefik.log"
level = "INFO"

[accessLog]
filePath = "/var/log/access.log"
format = "json"
